#!/bin/bash

# Check
if [ $# -lt 2 ]; then
  echo "Використання: kubectl kubeplugin <namespace> <kubectl resource command>"
  echo "Приклад: kubectl kubeplugin kube-system top pods"
  exit 1
fi

NAMESPACE=$1
shift
RESOURCE_COMMAND="$@"


# Head
echo "Resource, Namespace, Name, CPU, Memory"

# Отримання статистики...
kubectl $RESOURCE_COMMAND -n "$NAMESPACE" | tail -n +2 | while read -r line; do
  NAME=$(echo "$line" | awk '{print $1}')
  CPU=$(echo "$line" | awk '{print $2}')
  MEMORY=$(echo "$line" | awk '{print $3}')

  echo "$RESOURCE_COMMAND, $NAMESPACE, $NAME, $CPU, $MEMORY"
done

